//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organization_Website_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class connection
    {
        public int connection_id { get; set; }
        public int organization_id { get; set; }
        public int person_id { get; set; }
    
        public virtual organization organization { get; set; }
        public virtual person person { get; set; }
    }
}
